Update regular.txt
CanCLID/typo-corrector pull request #1
Opened 2023-10-20 10:12 UTC by indiejoseph

1. Remove 冧, it would mistakenly replacing 我冧你 to 我諗你
2. Add 啱[啦嘞]

2023-10-20 18:54 UTC, laubonghaudoi requested changes
唔該晒，麻煩改下呢兩行

2023-10-20 18:54 UTC, laubonghaudoi commented on regular.txt
> +丫,吖
呢行應該刪咗佢。「丫」字有可能搭配其他詞嘅，直接改成「吖」有好大風險。

2023-10-20 18:54 UTC, laubonghaudoi commented on regular.txt
> -([我你佢]) 冧,\1諗
點解要刪呢個呢？

2023-10-20 19:13 UTC, indiejoseph commented on regular.txt
> +丫,吖
Ok

2023-10-20 19:13 UTC, indiejoseph commented on regular.txt
> -([我你佢]) 冧,\1諗
我冧你 -> 我諗你

2023-10-20 20:19 UTC, laubonghaudoi commented on regular.txt
> -([我你佢]) 冧,\1諗
我覺得呢個冇問題，呢度嘅「諗」就係解作【思念】

2023-10-20 20:21 UTC, laubonghaudoi commented on regular.txt
> +丫,吖
唔好意思我唔係話刪第14行，我係話刪第16行，`丫,吖`

2023-10-20 20:23 UTC, indiejoseph commented on regular.txt
> -([我你佢]) 冧,\1諗
但如我有人同你講：「我好冧你 」，意思同「我好諗你」好唔同啵

2023-10-20 20:24 UTC, indiejoseph commented on regular.txt
> +丫,吖
我攪錯，thx

2023-10-20 22:46 UTC, graphemecluster commented on regular.txt
> +岩 ([啦嘞]),啱\1
```suggestion
岩 ([吖啊呀啦喇嘞]),啱\1
```

2023-10-20 22:47 UTC, laubonghaudoi commented on regular.txt
> -([我你佢]) 冧,\1諗
「我好lam3你」係個病句嚟嘅，現實中唔會講。只會講「我好nam1你」，就係「諗」

2023-10-21 06:25 UTC, indiejoseph commented on regular.txt
> -([我你佢]) 冧,\1諗
咁我改返先

2023-10-24 21:08 UTC, laubonghaudoi commented on regular.txt
> -([我你佢]) 冧,\1諗
或者可以用「惗」嚟表示 lam1，總之「冧」係 lam3

2023-10-24 21:09 UTC, laubonghaudoi approved these changes

2023-10-24 21:09 UTC, merged